# Generated by Django 5.2.8 on 2025-12-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_company_description_company_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
