# Generated by Django 5.2.8 on 2025-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='batch',
            field=models.CharField(blank=True, help_text='e.g. 2022, 2023, 2024', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='external_link',
            field=models.URLField(blank=True, help_text='External apply link (if any)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills, e.g. React, Django, REST API', null=True),
        ),
    ]
