# Generated by Django 5.2.8 on 2025-12-10 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobtest_jobtestquestion_jobtestanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_notifications', to='jobs.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
